{% set name = "ismrmrd-python" %}
{% set version = "1.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ismrmrd/ismrmrd-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c9aa37c1f4490571b75aefdbeeb92045ae28217ba2c47655a960e007a47f856c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6,<3.12
    - setuptools
    - wheel
    - xsdata >22
    - jinja2 >=2.11.0
    - nose >=1.0
    - pip
  run:
    - python >=3.6,<3.12
    - xsdata >=22.12,<23
    - numpy >=1.22.0
    - h5py >=2.3

test:
  imports:
    - ismrmrd
  source_files:
    - tests
  commands:
    - pip check
    - nosetests
  requires:
    - pip
    - nose

about:
  home: https://ismrmrd.github.io
  summary: Python implementation of the ISMRMRD
  description: |
    Python interface and utilities for the ISMRM Raw Data (ISMRMRD a.k.a. MRD) format.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/ismrmrd/ismrmrd-python
  doc_url: https://github.com/ismrmrd/ismrmrd-python
  doc_source_url: https://github.com/ismrmrd/ismrmrd-python/blob/main/README.md

extra:
  recipe-maintainers:
    - gabuzi
